/* eslint-disable @next/next/next-script-for-ga */
import Document, { Html, Head, Main, DocumentContext, NextScript } from 'next/document';
import Script from 'next/script';

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="My name is Kacper Latuszewski. I'm a student. In love with functional programming |> Elixir, Erlang. I also create a frontend in React."></meta>
          <meta name="author" content="Kacper Latuszewski" />
          <meta name="keywords" content="latuszewski, kacper, latuszewski, kacper latuszewski, developer, server-side, backend, functional programming, programming, web development, elixir, phoenix, erlang, react" />
          <meta property="og:title" content="Kacper Latuszewski" />
          <meta property="og:description" 
            content="My name is Kacper Latuszewski. I'm a student. In love with functional programming |> Elixir, Erlang. Mostly writing backend but I also create a frontend in React." />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://latuszewski.pl" />

          <link rel="icon" href="/favicon.ico" />

          <Script src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`} strategy="afterInteractive" />
          <Script
            id="analytics"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag() { dataLayer.push(arguments); }
              gtag('js', new Date());
              gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');');
              `,
            }}
          />

        </Head>
        <body>
          <NextScript />
          <Main />
        </body>
      </Html>
    )
  }
}

export default MyDocument