import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [nextPage, setNextPage] = useState<boolean>(true);

  const handleKeyPress = (e: KeyboardEvent) => {
    const key = " ";
    if(e.key === key){
      setNextPage(prev => !prev)
    }
  }

  useEffect(() => {
    window.addEventListener('keydown', handleKeyPress);
    return () => {
      window.removeEventListener('keydown', handleKeyPress);
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}><a href="https://appunite.com/"></a>Blog</nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Latuszewski
        </h1>
        <p className={styles.description}>Software Engineer at <a href="https://appunite.com/" target="_blank" rel="noreferrer">@appunite</a> and Elixir zealot.</p>
      </main>

    </div>
  )
}


export default Home
